services:
   vue-dev:
      image: node:20
      container_name: vue-dev-container
      restart: always
      working_dir: /app
      ports:
        - 5173:5173
      volumes:
        - ./:/app
      entrypoint: sleep infinity
